#!/usr/bin/env bash

# ------------------------------------------------------------------------
# Figure out which bit-type of PGI/pgf95 we are using:
# ------------------------------------------------------------------------
# "pgf95 -show" contains information on the bit version (32 or 64) via the
# variable TARGETARCH, which is either 64 or 32.
# ------------------------------------------------------------------------
ifort -V >& compiler.txt
BITVERSION=$(cat compiler.txt | grep 64 | wc -l)
if [ ${BITVERSION} -eq 0 ]; then
   BV=32
else
   BV=64
fi
rm -f compiler.txt

export FLAVOR=linux${BV}

export OMIUTIL=/data/dumbo/gonzalo/lib/Intel

source ${OMIUTIL}/toolkit/bin/${FLAVOR}/pgs-dev-env.ksh
export MACHINE=`uname -a | awk '{print $2}'`

export SAOPGE=`(cd ../; pwd | awk -F "/" '{print $NF}')`
echo 'Compiling ' ${SAOPGE}'.exe for machine ' ${MACHINE}

export PGEHOME=`pwd`/..
export PGS_PC_INFO_FILE=${PGEHOME}/src/${SAOPGE}.pcf
export PGEVERSION=`grep PGEVERSION ${PGS_PC_INFO_FILE}|sed 's/\"//g'|sed 's/|/ /g'|awk '{print $3}'`
export PGEIODIR=${PGEHOME}/out
export OMISAOSHARED=../../OMI_SAO_Shared_VOCs
export UTDATADIR=/data/tempo2/ggonzale/OMH2O/inputs
export UTDATAINS=${UTDATADIR}
export UTDATAOUT=${UTDATADIR}

export MACHSHELL=/bin/ksh
export PGSMSG=${PGEHOME}/bin
export MKFDIR=`pwd`/../../nonTLCF_Make_VOCs
gmake --warn-undefined-variables -f ${MKFDIR}/Makefile.non-TLCF $1
echo 'EXIT VALUE of Make Process is ' `echo $?`
