#!/usr/bin/env bash

# ---------------------------------------------------------------------
# Following TLCF migration to gfortran 64bit this is the only compiling
# possibility
# ---------------------------------------------------------------------
export OMIUTIL=/data/tempo2/ggonzale/TEMPO_code/ots/gnu

source ${OMIUTIL}/sdptk/SDPTK5.2.19v1.00/TOOLKIT/bin/linux/pgs-dev-env.ksh
export MACHINE=`uname -a | awk '{print $2}'`

export SAOPGE=`(cd ../; pwd | awk -F "/" '{print $NF}')`
echo 'Compiling ' ${SAOPGE}'.exe for machine ' ${MACHINE}

export PGEHOME=`pwd`/..
export PGS_PC_INFO_FILE=${PGEHOME}/src/${SAOPGE}.pcf
export PGEVERSION=`grep PGEVERSION ${PGS_PC_INFO_FILE}|sed 's/\"//g'|sed 's/|/ /g'|awk '{print $3}'`
export PGEIODIR=${PGEHOME}/out
export OMISAOSHARED=../../OMI_SAO_Shared_VOCs
export UTDATADIR=/data/tempo2/ggonzale/OMH2O/inputs
export UTDATAINS=${UTDATADIR}
export UTDATAOUT=${UTDATADIR}

export MACHSHELL=/bin/ksh
export PGSMSG=${PGEHOME}/bin
export MKFDIR=`pwd`/../../nonTLCF_Make_VOCs
gmake --warn-undefined-variables -f ${MKFDIR}/Makefile.non-TLCF $1
echo 'EXIT VALUE of Make Process is ' `echo $?`
