#!/usr/bin/env bash

  PCF=$1

  export APPHOME=$(pwd | sed "s/\/src//1")
  export SAOAPP=$(basename ${APPHOME})
  export IODIR=${APPHOME}/out

  ifort -V >& compiler.txt
  BITVERSION=$(cat compiler.txt | grep 64 | wc -l)
  if [ ${BITVERSION} -eq 0 ]; then
      BV=32
  else
      BV=64
  fi
  rm -f compiler.txt
  
  export FLAVOR=linux${BV}

  export OMIUTIL=/data/dumbo/gonzalo/lib/Intel

  source ${OMIUTIL}/toolkit/bin/${FLAVOR}/pgs-dev-env.ksh
  
  export PGS_PC_INFO_FILE=${APPHOME}/src/${PCF}
  export PGSMSG=${APPHOME}/bin

  gmake -f ../../nonTLCF_Make_VOCs/Makefile.RunIt run

