#!/usr/bin/env bash

PCF=$1

export APPHOME=$(pwd | sed "s/\/src//1")
export SAOAPP=$(basename ${APPHOME})
export IODIR=${APPHOME}/out

BITVERSION=$(file IODIR}/${SAOAPP}.exe | grep 64-bit | wc -l)
if [ ${BITVERSION} -eq 0 ]; then
   BV=32
else
   BV=64
fi

export HDF5V=v16
export FLAVOR=linux${BV}

export OMIUTIL=/usr/local/hdfutils/${BV}bit
source ${OMIUTIL}/toolkit_${HDF5V}/bin/${FLAVOR}/pgs-dev-env.ksh

export PGS_PC_INFO_FILE=${APPHOME}/src/${PCF}
export PGSMSG=${APPHOME}/bin

gmake -f ../../nonTLCF_Make/Makefile.RunIt run

#cd ${IODIR}; ${IODIR}/${SAOAPP}.exe; echo 'EXIT VALUE of PGE run is ' $?
